services:
  ac-db-import:
    environment:
      AC_PLAYERBOTS_DATABASE_INFO: "ac-database;3306;root;${DOCKER_DB_ROOT_PASSWORD:-password};acore_playerbots"

  ac-worldserver:
    environment:
      AC_AI_PLAYERBOT_ENABLED: "1"
      AC_AI_PLAYERBOT_RANDOM_BOT_AUTOLOGIN: "1"
      AC_AI_PLAYERBOT_MIN_RANDOM_BOTS: "1000"
      AC_AI_PLAYERBOT_MAX_RANDOM_BOTS: "1000"
      AC_PLAYER_LIMIT: "0"
      AC_MAP_UPDATE_THREADS: "4"
      AC_SOAP_ENABLED: "1"
      AC_SOAP_IP: "0.0.0.0"
      AC_SOAP_PORT: "7878"
    volumes:
      - ./modules:/azerothcore/modules:ro
      - ./conf/dist/modules/playerbots.conf:/azerothcore/env/dist/etc/modules/playerbots.conf:ro
      - ./conf/dist/modules/mod_ahbot.conf:/azerothcore/env/dist/etc/modules/mod_ahbot.conf:ro
